FROM alpine:latest
LABEL multi.description="Image running smartX web interface on x64 Linux" \
multi.version="1.0"
EXPOSE 80

ENV http_proxy "http://10.254.1.13:8080"
ENV https_proxy "http://10.254.1.13:8080"

RUN apk add --update nginx curl && rm -rf /var/cache/apk/*

RUN curl -k -L https://github.com/djey47/smartX/raw/master/release/smartX-webapp-20141019.R1.08.tar.gz > /tmp/smartX.tar.gz

RUN mkdir /run/nginx

RUN mkdir -p /opt/smartX

RUN tar xzf /tmp/smartX.tar.gz -C /opt/smartX && rm /tmp/smartX.tar.gz

ADD server/nginx.conf /etc/nginx/
ADD server/start-x64.sh /opt/

WORKDIR /opt/smartX
CMD ["/opt/start-x64.sh"]
